### ISSUE TITLE
Please fill the requirements.txt 

### ISSUE THREAD

**Issue by f13o** [Beauchef-Proyecta/mlf-service#1]
I want to test this code, but `requirements.txt` is empty and I can't guess the dependencies and their versions by just looking at the imports.

Please run `pip freeze > requirements.txt` to update the file an then push it to either `main` or `dev`.

This will allow anyone to run the code on their own environments :)

Also, which Python version are you running this project on? 
If you just run `python3 core/example.py`, then you can know the version by running `python3 --version`

**Comment by matiasguzmanp** [comment]
Requirements are updated. Also, Python version is now showed on README. I'm closing this issue.
